#!/bin/sh
#0.4 kal_q_sym

kallisto quant -i kal_in_sym -o ksym907 --single cl_907.fasta
kallisto quant -i kal_in_sym -o ksym908 --single cl_908.fasta
kallisto quant -i kal_in_sym -o ksym909 --single cl_909.fasta
kallisto quant -i kal_in_sym -o ksym910 --single cl_910.fasta
kallisto quant -i kal_in_sym -o ksym911 --single cl_911.fasta
kallisto quant -i kal_in_sym -o ksym912 --single cl_912.fasta
kallisto quant -i kal_in_sym -o ksym913 --single cl_913.fasta
kallisto quant -i kal_in_sym -o ksym914 --single cl_914.fasta
kallisto quant -i kal_in_sym -o ksym915 --single cl_915.fasta
kallisto quant -i kal_in_sym -o ksym916 --single cl_916.fasta
kallisto quant -i kal_in_sym -o ksym917 --single cl_917.fasta
kallisto quant -i kal_in_sym -o ksym918 --single cl_918.fasta
kallisto quant -i kal_in_sym -o ksym919 --single cl_919.fasta
kallisto quant -i kal_in_sym -o ksym920 --single cl_920.fasta
kallisto quant -i kal_in_sym -o ksym921 --single cl_921.fasta
kallisto quant -i kal_in_sym -o ksym922 --single cl_922.fasta
kallisto quant -i kal_in_sym -o ksym923 --single cl_923.fasta
kallisto quant -i kal_in_sym -o ksym924 --single cl_924.fasta
kallisto quant -i kal_in_sym -o ksym925 --single cl_925.fasta
kallisto quant -i kal_in_sym -o ksym926 --single cl_926.fasta
kallisto quant -i kal_in_sym -o ksym927 --single cl_927.fasta
kallisto quant -i kal_in_sym -o ksym928 --single cl_928.fasta
kallisto quant -i kal_in_sym -o ksym929 --single cl_929.fasta
kallisto quant -i kal_in_sym -o ksym930 --single cl_930.fasta
kallisto quant -i kal_in_sym -o ksym931 --single cl_931.fasta
kallisto quant -i kal_in_sym -o ksym932 --single cl_932.fasta
kallisto quant -i kal_in_sym -o ksym933 --single cl_933.fasta
kallisto quant -i kal_in_sym -o ksym934 --single cl_934.fasta
kallisto quant -i kal_in_sym -o ksym935 --single cl_935.fasta
kallisto quant -i kal_in_sym -o ksym936 --single cl_936.fasta
kallisto quant -i kal_in_sym -o ksym937 --single cl_937.fasta
kallisto quant -i kal_in_sym -o ksym938 --single cl_938.fasta
kallisto quant -i kal_in_sym -o ksym939 --single cl_939.fasta
kallisto quant -i kal_in_sym -o ksym940 --single cl_940.fasta
kallisto quant -i kal_in_sym -o ksym941 --single cl_941.fasta
kallisto quant -i kal_in_sym -o ksym942 --single cl_942.fasta
kallisto quant -i kal_in_sym -o ksym943 --single cl_943.fasta
kallisto quant -i kal_in_sym -o ksym944 --single cl_944.fasta
kallisto quant -i kal_in_sym -o ksym945 --single cl_945.fasta
kallisto quant -i kal_in_sym -o ksym946 --single cl_946.fasta
kallisto quant -i kal_in_sym -o ksym947 --single cl_947.fasta
kallisto quant -i kal_in_sym -o ksym948 --single cl_948.fasta
